name: Playwright Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '14'  # Adjust to your version
        postgresql db: 'test_db'   # Name of the test database you want to create
        postgresql user: 'postgres'  # Default PostgreSQL user
        postgresql password: 'password'  # Password for the 'postgres' user
    - name: Set environment variables
      run: echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/test_db?schema=public" >> $GITHUB_ENV
    - name: Set environment variables 2
      run: echo "AUTH_SECRET='YOUR_AUTH_SECRET'" >> $GITHUB_ENV
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Run Prisma migrations
      run: npx prisma migrate deploy
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
